volumes:
  postgres_data:
services:
  postgres:
    image: postgres:17.5-alpine
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pa55word
      POSTGRES_USER: head_agent
      POSTGRES_DB: sca
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
