// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateTargets implements pgx.CopyFromSource.
type iteratorForCreateTargets struct {
	rows                 []CreateTargetsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTargets) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTargets) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].MissionID,
		r.rows[0].Name,
		r.rows[0].Country,
		r.rows[0].Notes,
		r.rows[0].State,
	}, nil
}

func (r iteratorForCreateTargets) Err() error {
	return nil
}

func (q *Queries) CreateTargets(ctx context.Context, arg []CreateTargetsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"targets"}, []string{"id", "mission_id", "name", "country", "notes", "state"}, &iteratorForCreateTargets{rows: arg})
}
