// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID           int64
	Name         string
	PasswordHash []byte
}

type Mission struct {
	ID       int64
	State    string
	SpyCatID pgtype.Int8
}

type SpyCat struct {
	ID                int64
	Name              string
	PasswordHash      []byte
	YearsOfExperience int32
	Breed             string
	Salary            float64
}

type Target struct {
	ID        int64
	Name      string
	Country   string
	Notes     string
	State     string
	MissionID int64
}

type Token struct {
	Hash     []byte
	UserID   int64
	UserType string
	Expiry   pgtype.Timestamptz
	Scope    string
}
